server:
  port: 8081
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka
      #eureka集群
      defaultZone: http://peer1.com:8761/eureka/,http://peer2.com:8762/eureka/,http://peer3.com:8763/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    #hostname: localhost
spring:
  # 应用到eureka中，对应着VIP Adress
  application:
    name: shop-service
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"